version: '3'

services:
    # The HADatAc Solr service
    solr:
        image: tetherlessworld/nhanes-hadatac_solr:latest
        container_name: nhanes-hadatac_solr
        restart: always
        environment:
            SOLR_JAVA_MEM: "-Xms1g -Xmx1g"
        networks:
            hadatac:
                aliases:
                    - solr
        ports:
            - "8983:8983"

    # The HADatAc Blazegraph service
    blazegraph:
        image: tetherlessworld/nhanes-hadatac_blazegraph:latest
        container_name: nhanes-hadatac_blazegraph
        networks:
            hadatac:
                aliases:
                    - blazegraph
        ports:
            - "8080:8080"
        restart: always
        environment:
            JAVA_OPTS: -Xms128m -Xmx2g

    # The main HADatAc web app
    hadatac:
        image: tetherlessworld/nhanes-hadatac:latest
        restart: always
        container_name: nhanes-hadatac
        tty: true
        ports:
            - "9000:9000"
        networks:
            hadatac:
                aliases:
                    - hadatac
        environment:
            JAVA_OPTS: -Xms128m -Xmx12g
        volumes:
            - /var/log/hadatac:/hadatac/logs
        links:
            - blazegraph
            - solr
        depends_on:
            - blazegraph
            - solr

    # Jupyter Lab
    jupyter:
        image: tetherlessworld/nhanes-hadatac_jupyter:latest
        build: nhanes-hadatac_jupyter/
        restart: always
        container_name: nhanes-hadatac_jupyter
        environment:
            - NOTEBOOK_ARGS=--VoilaConfiguration.strip_sources=False
        ports:
            - "8888:8888"
        networks:
            hadatac:
                aliases:
                    - jupyter
        links:
            - hadatac
        depends_on:
            - hadatac

networks:
    hadatac:
